# ProactiveCachePress — KVPress plugin for Proactive KV Cache Eviction.
#
# Usage:
#   from phase6.proactive_cache_press import ProactiveCachePress
#   press = ProactiveCachePress(compression_ratio=0.25, prototype_path="outputs/phase4/...")
#
# Integration with KVPress standard evaluation:
#   python phase6/kvpress_benchmark.py
#
# Reference: https://github.com/NVIDIA/kvpress

# Shim for Python 3.13+ which removed the 'pipes' module (needed by fire/kvpress)
try:
    import pipes
except ImportError:
    import sys, shlex
    sys.modules['pipes'] = shlex

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import torch
import pickle
import numpy as np
from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# KVPress ScorerPress compatibility shim
# We inherit from ScorerPress if kvpress is installed, otherwise provide a
# minimal stand-alone interface so the module imports without kvpress.
# ---------------------------------------------------------------------------
try:
    from kvpress import ScorerPress
    _KVPRESS_AVAILABLE = True
except ImportError:
    _KVPRESS_AVAILABLE = False

    class ScorerPress:
        """Minimal shim so ProactiveCachePress can be imported without kvpress installed."""
        def __init__(self):
            self.compression_ratio = 0.0

        def score(self, module, hidden_states, keys, values, attentions, kwargs):
            raise NotImplementedError


@dataclass
class ProactiveCachePress(ScorerPress):
    """
    Proactive KV cache eviction via frozen attention-head prototypes.

    Profiles attention patterns offline (once) and at inference time uses the
    resulting prototype centroids to score each KV position without looking at
    query activations — making it O(n) per forward pass rather than O(n²).

    Args:
        compression_ratio: Fraction of the KV cache to EVICT  [0.0, 1.0).
            e.g. 0.75 keeps only 25% of tokens (budget = seq_len * 0.25).
        prototype_path: Absolute path to a prototypes .pkl file generated by
            phase4/profile_llama.py. If None, falls back to uniform scoring.
    """
    compression_ratio: float = 0.5
    prototype_path: str = None

    def __post_init__(self):
        self._prototypes = None
        if self.prototype_path and os.path.exists(self.prototype_path):
            with open(self.prototype_path, "rb") as f:
                self._prototypes = pickle.load(f)
            print(f"[ProactiveCachePress] Loaded prototypes from {self.prototype_path}")
        else:
            print("[ProactiveCachePress] WARNING: No prototype file found — using uniform scoring.")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _score_tokens_proactive(self, seq_len: int, budget: int) -> np.ndarray:
        """
        Score all token positions using prototype centroid histograms.
        Returns a (seq_len,) float64 array — higher score = more important.
        """
        scores = np.zeros(seq_len, dtype=np.float64)

        for (layer, head) in self._prototypes.keys():
            centroid = self._prototypes[(layer, head)]["centroids"][0]
            max_d = min(len(centroid), seq_len)
            if max_d == 0:
                continue
            cumsum = np.cumsum(centroid[:max_d])
            for p in range(seq_len):
                reach = min(max_d, seq_len - p)
                if reach > 0:
                    scores[p] += cumsum[reach - 1]

        # Attention sink boost — token 0 is always critical
        scores[0] += scores.max() * 10.0

        # Budget-proportional local recency window
        recency_window = min(max(8, budget // 16), seq_len)
        for i in range(recency_window):
            scores[seq_len - 1 - i] += scores.max() * max(0.5, 5.0 - i * 0.5)

        # Small deterministic tiebreaker
        scores += np.linspace(0, 0.001, seq_len)
        return scores

    # ------------------------------------------------------------------
    # KVPress API
    # ------------------------------------------------------------------

    def score(self, module, hidden_states, keys, values, attentions, kwargs):
        """
        KVPress hook: called once per layer during prefill.

        Args:
            module:        The attention module (provides module.layer_idx).
            hidden_states: (batch, seq_len, hidden_dim)
            keys:          (batch, num_heads, seq_len, head_dim)
            values:        (batch, num_heads, seq_len, head_dim)
            attentions:    Attention weights if available, else None.
            kwargs:        Extra forward kwargs.

        Returns:
            scores: (batch, num_heads, seq_len) float tensor.
                    Lower score = higher eviction priority (KVPress convention).
        """
        batch_size, num_heads, seq_len, head_dim = keys.shape
        budget = max(1, int(seq_len * (1.0 - self.compression_ratio)))
        device = keys.device

        if self._prototypes is None:
            # Fallback: uniform scoring (keep all tokens equally)
            return torch.ones(batch_size, num_heads, seq_len, device=device)

        # Build prototype scores once for this sequence length (cached for O(1) retrieval)
        if not hasattr(self, "_score_cache"):
            self._score_cache = {}
        
        cache_key = (seq_len, budget)
        if cache_key in self._score_cache:
            proto_scores = self._score_cache[cache_key]
        else:
            proto_scores = self._score_tokens_proactive(seq_len, budget)
            self._score_cache[cache_key] = proto_scores

        proto_tensor = torch.tensor(proto_scores, dtype=torch.float32, device=device)

        # Broadcast across batch and heads: (1, 1, seq_len) → (B, H, seq_len)
        scores = proto_tensor.unsqueeze(0).unsqueeze(0).expand(batch_size, num_heads, seq_len)
        return scores.contiguous()


# ---------------------------------------------------------------------------
# Stand-alone test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Test ProactiveCachePress stand-alone")
    parser.add_argument("--proto", type=str, default=None,
                        help="Path to prototype pkl file")
    parser.add_argument("--compression-ratio", type=float, default=0.5)
    args = parser.parse_args()

    press = ProactiveCachePress(
        compression_ratio=args.compression_ratio,
        prototype_path=args.proto,
    )
    print(f"ProactiveCachePress created. compression_ratio={press.compression_ratio}")
    print(f"  KVPress available: {_KVPRESS_AVAILABLE}")
    print(f"  Prototypes loaded: {press._prototypes is not None}")
    if press._prototypes is not None:
        print(f"  Prototype keys (first 3): {list(press._prototypes.keys())[:3]}")
